FROM python:2.7.13

RUN apt-get update && apt-get install -y build-essential
RUN git clone https://github.com/StephenTurley/spacy-services.git
WORKDIR /spacy-services/displacy

RUN pip install -r requirements.txt
RUN python -m spacy download en

CMD ["python","app.py"]

