FROM node:5.1

RUN apt-get update && apt-get install -y build-essential
RUN git clone https://github.com/StephenTurley/displacy.git
WORKDIR /displacy

RUN npm install -g harp
RUN npm install

CMD ["harp","server"]

