FROM python:2.7.13

RUN apt-get update && apt-get install -y build-essential
RUN git clone -b 0.0.1 https://github.com/StephenTurley/spacy-services.git

WORKDIR /spacy-services/displacy

RUN pip install -r requirements.txt
RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
RUN python -m spacy link en_core_web_sm en

CMD ["python","app.py"]

